version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: marketing
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
    ports:
      - "5050:80"
    depends_on:
      - db

  go-app:
    container_name: go_app
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin@123
      DB_NAME: marketing
      SERVER_PORT: 8080

volumes:
  pg_data:
